using OpenaiResponsesApiToolCall.Extension;
using OpenaiResponsesApiToolCall.Interfaces;
using OpenaiResponsesApiToolCall.Services;
using System.Text;
using System.Text.Json;

namespace OpenaiResponsesApiToolCall.LLM
{
    internal static class OpenAILLM
    {
        public static async IAsyncEnumerable<string> GetStreamingResponseAsync(OpenaiApiHttpClient client, string prompt, IFunctionTools tools)
        {
            string llm = "gpt-5-2025-08-07";

            var input_list = new List<object>
            {
                new { role = "user", content = prompt }
            };

            var requestPayload = new
            {
                model = llm,
                instructions = "You are an assistant that can call tools.",
                input = input_list.ToArray(),
                tools = tools.Definition()
            };

            var content = new StringContent(JsonSerializer.Serialize(requestPayload), Encoding.UTF8, "application/json");
            using var doc = await client.PostPayloadWithReturnJsonDocumentAsync(string.Empty, content);
            var root = doc.RootElement;
            var output = root.GetProperty("output");
            var outputArray = output.EnumerateArray();

            var outputObj = JsonSerializer.Deserialize<object[]>(output);
            if (outputObj == null)
            {
                throw new Exception("Model returned no output.");
            }
            input_list.AddRange(outputObj);

            bool hasToolCall = false;
            List<JsonElement> followUpMessages = new List<JsonElement>();
            foreach (var item in outputArray)
            {
                var itemType = item.GetProperty("type").GetString();
                if (string.Compare(itemType, "function_call", true) == 0)
                {
                    hasToolCall = true;
                    string? funcName = item.GetProperty("name").GetString();
                    string? argsJson = item.GetProperty("arguments").GetString();

                    yield return $"Model requested function: {funcName} with arguments: {argsJson}.";

                    var funcResult = await tools.Implementation(funcName, argsJson);
                    string? toolCallId = item.GetProperty("id").GetString();

                    var toolMsg = new
                    {
                        type = "function_call_output",
                        call_id = item.GetProperty("call_id").GetString(),
                        output = JsonSerializer.Serialize(funcResult)
                    };

                    input_list.Add(toolMsg);
                }
            }

            if (hasToolCall)
            {
                yield return "Following up ...";

                var followupPayload = new
                {
                    model = llm,
                    instructions = "Respond with results generated by a tool.",
                    input = input_list.ToArray(),
                    tools = tools.Definition()
                };

                var followupContent = new StringContent(JsonSerializer.Serialize(followupPayload), Encoding.UTF8, "application/json");
                using var followupResultDoc = await client.PostPayloadWithReturnJsonDocumentAsync(string.Empty, followupContent);

                var followupResultRoot = followupResultDoc.RootElement;
                var followupResultOutput = followupResultRoot.GetProperty("output");
                var followupResultOutputArray = followupResultOutput.EnumerateArray();

                foreach (var item in followupResultOutputArray)
                {
                    string? itemType = item.GetProperty("type").GetString();
                    if (string.Compare(itemType, "message", true) == 0)
                    {
                        var outputContent = item.GetProperty("content");
                        var outputContentArray = outputContent.EnumerateArray();
                        foreach (var contentItem in outputContentArray)
                        {
                            string? contentItemType = contentItem.GetProperty("type").GetString();
                            if (string.Compare(contentItemType, "output_text", true) == 0)
                            {
                                string? text = contentItem.GetProperty("text").GetString();
                                yield return text ?? string.Empty;
                            }
                        }
                    }
                }
            }
        }
    }
}
